# This is a Taskfile. It will help you do the things.
# https://taskfile.dev/#/installation

version: '3'

tasks:
  serve:
    desc: Serve the page
    cmds:
      - hugo serve --buildDrafts

  publish:
    desc: Publish the HTML.
    vars:
      DIRECTORY: /nest/srv/trans-hub
    cmds:
      - hugo --buildFuture --destination {{.DIRECTORY}}

  ci:publish:
    desc: Publish the HTML, and also pull git before
    vars:
      DIRECTORY: /nest/srv/trans-hub
    cmds:
      - git pull origin main
      - hugo --buildFuture --destination {{.DIRECTORY}}
